services:
  - type: web
    name: telegram-python-bot
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-2.5-flash
      - key: ABA_MERCHANT_ID
        value: ec477154
      - key: ABA_API_KEY
        value: 758d62f9bc45bf0322aadf778999bf833a9d68a0
      - key: ABA_PAYWAY_URL
        value: https://checkout-sandbox.payway.com.kh/api/payment-gateway/v1/payments/purchase
      - key: SERVER_URL
        sync: false


