import { sanitizeHtmlText } from '../../utils/sanitize';

export function renderSolutionViewHtml(solutionData: any, publicId: string, appUrl: string, botUsername: string): string {
  const data = solutionData.structuredResult || solutionData;
  const questions = data.questions || [];
  const q1 = questions[0] || {};
  const problemLatex = q1.question_latex || '\\left(1-\\frac{1}{2}\\right)\\left(1-\\frac{1}{3}\\right)\\cdots\\left(1-\\frac{1}{2024}\\right)';
  const problemRaw = q1.original_question || '(1 - 1/2)(1 - 1/3)...(1 - 1/2024)';
  const steps = q1.steps || [];
  const finalAnswerLatex = q1.final_answer_latex || '\\frac{1}{2024}';
  const notes = data.notes || [];

  const subject = solutionData.subject || data.subject || 'Mathematics';
  const topic = solutionData.topic || data.topic || 'Fractions';
  const difficulty = solutionData.difficulty || data.difficulty || 'Easy';
  const generatedAt = solutionData.generatedAt || 'July 23, 2026';
  const generatedTime = solutionData.generatedTime || '10:22 AM';
  const modelName = solutionData.modelName || 'Smart AI Math Solver';
  const summaryText = solutionData.summary || 'សម្រួលកត្តានីមួយៗនៃផលគុណប្រភាគ រួចធ្វើការសម្រួលភាគយក និងភាគបែងដែលដូចគ្នាតាមលំនាំតទល់ (Telescoping Product)។';

  const telegramBotUrl = `https://t.me/${botUsername || 'mysmart_v2_2026_bot'}`;

  return `<!DOCTYPE html>
<html lang="km">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>#${publicId.toUpperCase()} Solution | Smart AI Math Solver</title>
  
  <!-- Primary Meta Tags -->
  <meta name="title" content="Problem #${publicId.toUpperCase()} Solution | Smart AI Math Solver">
  <meta name="description" content="Official step-by-step ${subject} solution generated by Smart AI Math Solver. Problem: ${sanitizeHtmlText(problemRaw)}">
  
  <!-- Open Graph / Facebook / Telegram -->
  <meta property="og:type" content="website">
  <meta property="og:url" content="${appUrl}/solution/${publicId}">
  <meta property="og:title" content="Problem #${publicId.toUpperCase()} Solution | Smart AI Math Solver">
  <meta property="og:description" content="Step-by-step ${subject} solution generated by Smart AI Math Solver.">
  <meta property="og:image" content="${appUrl}/public/og-image.png">

  <!-- Twitter -->
  <meta property="twitter:card" content="summary_large_image">
  <meta property="twitter:url" content="${appUrl}/solution/${publicId}">
  <meta property="twitter:title" content="Problem #${publicId.toUpperCase()} Solution | Smart AI Math Solver">

  <!-- KaTeX CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css">
  
  <!-- Fonts: Noto Sans Khmer & Inter -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Noto+Sans+Khmer:wght@400;500;600;700&display=swap" rel="stylesheet">
  
  <!-- Lucide Icons -->
  <script src="https://unpkg.com/lucide@latest"></script>
  <!-- KaTeX Auto-Render -->
  <script src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js"></script>

  <style>
    :root {
      --primary-dark: #123B8F;
      --primary-blue: #2563EB;
      --primary-bright: #3B82F6;
      
      --bg-main: #F6F9FD;
      --bg-card: #FFFFFF;
      --bg-soft-blue: #EFF6FF;
      --bg-soft-green: #F0FDF4;
      --bg-soft-purple: #FAF5FF;
      
      --text-main: #0F172A;
      --text-secondary: #475569;
      --text-muted: #64748B;
      --border-color: #E2E8F0;
      
      --status-success: #16A34A;
      --status-warning: #D97706;
      --status-error: #DC2626;
      
      --radius-sm: 8px;
      --radius-card: 16px;
      --radius-lg: 24px;
      
      --shadow-sm: 0 1px 2px 0 rgba(0, 0, 0, 0.05);
      --shadow-card: 0 4px 20px -2px rgba(18, 59, 143, 0.06), 0 2px 6px -1px rgba(0, 0, 0, 0.04);
      --shadow-hover: 0 10px 30px -4px rgba(37, 99, 235, 0.12);
    }

    * { box-sizing: border-box; margin: 0; padding: 0; }

    body {
      font-family: 'Noto Sans Khmer', 'Inter', -apple-system, sans-serif;
      background-color: var(--bg-main);
      color: var(--text-main);
      line-height: 1.6;
      -webkit-font-smoothing: antialiased;
    }

    /* Sticky Navigation Header */
    .navbar {
      position: sticky;
      top: 0;
      z-index: 100;
      background: rgba(255, 255, 255, 0.95);
      backdrop-filter: blur(8px);
      border-bottom: 1px solid var(--border-color);
      box-shadow: var(--shadow-sm);
    }

    .nav-container {
      max-width: 1440px;
      margin: 0 auto;
      padding: 12px 24px;
      display: flex;
      align-items: center;
      justify-content: space-between;
    }

    .brand-logo {
      display: flex;
      align-items: center;
      gap: 12px;
      text-decoration: none;
    }

    .brand-icon {
      width: 42px;
      height: 42px;
      background: linear-gradient(135deg, var(--primary-dark) 0%, var(--primary-blue) 100%);
      border-radius: 12px;
      display: flex;
      align-items: center;
      justify-content: center;
      color: white;
      box-shadow: 0 4px 10px rgba(37, 99, 235, 0.25);
    }

    .brand-title {
      font-size: 18px;
      font-weight: 700;
      color: var(--primary-dark);
      line-height: 1.2;
    }

    .brand-subtitle {
      font-size: 12px;
      color: var(--text-muted);
      font-weight: 500;
    }

    .nav-links {
      display: flex;
      align-items: center;
      gap: 28px;
      list-style: none;
    }

    .nav-links a {
      text-decoration: none;
      color: var(--text-secondary);
      font-weight: 600;
      font-size: 14px;
      transition: color 0.15s ease;
    }

    .nav-links a:hover, .nav-links a.active {
      color: var(--primary-blue);
    }

    .nav-actions {
      display: flex;
      align-items: center;
      gap: 12px;
    }

    .btn {
      display: inline-flex;
      align-items: center;
      gap: 8px;
      padding: 8px 16px;
      border-radius: var(--radius-sm);
      font-size: 14px;
      font-weight: 600;
      cursor: pointer;
      text-decoration: none;
      transition: all 0.2s ease;
      border: 1px solid transparent;
    }

    .btn-primary {
      background: var(--primary-blue);
      color: white;
      box-shadow: 0 2px 8px rgba(37, 99, 235, 0.2);
    }

    .btn-primary:hover {
      background: var(--primary-dark);
    }

    .btn-outline {
      background: white;
      border-color: var(--border-color);
      color: var(--text-secondary);
    }

    .btn-outline:hover {
      background: var(--bg-soft-blue);
      border-color: var(--primary-bright);
      color: var(--primary-blue);
    }

    .lang-switcher {
      display: flex;
      background: var(--bg-main);
      padding: 3px;
      border-radius: var(--radius-sm);
      border: 1px solid var(--border-color);
    }

    .lang-btn {
      padding: 4px 10px;
      font-size: 12px;
      font-weight: 700;
      border-radius: 6px;
      border: none;
      background: transparent;
      color: var(--text-muted);
      cursor: pointer;
    }

    .lang-btn.active {
      background: white;
      color: var(--primary-blue);
      box-shadow: var(--shadow-sm);
    }

    .mobile-menu-toggle {
      display: none;
      background: none;
      border: none;
      color: var(--text-main);
      cursor: pointer;
    }

    /* Page Container */
    .main-wrapper {
      max-width: 1440px;
      margin: 0 auto;
      padding: 32px 24px;
    }

    /* Solution Header Header */
    .solution-header-card {
      background: var(--bg-card);
      border-radius: var(--radius-card);
      padding: 24px 32px;
      border: 1px solid var(--border-color);
      box-shadow: var(--shadow-card);
      margin-bottom: 24px;
      display: flex;
      flex-wrap: wrap;
      align-items: center;
      justify-content: space-between;
      gap: 20px;
    }

    .solution-title-box h1 {
      font-size: 24px;
      font-weight: 700;
      color: var(--primary-dark);
      display: flex;
      align-items: center;
      gap: 12px;
    }

    .verified-badge {
      display: inline-flex;
      align-items: center;
      gap: 6px;
      background: var(--bg-soft-green);
      color: var(--status-success);
      border: 1px solid rgba(22, 163, 74, 0.2);
      padding: 4px 12px;
      border-radius: 9999px;
      font-size: 13px;
      font-weight: 600;
    }

    .meta-pills {
      display: flex;
      flex-wrap: wrap;
      gap: 12px;
      margin-top: 12px;
    }

    .meta-pill {
      font-size: 13px;
      color: var(--text-secondary);
      background: var(--bg-main);
      padding: 4px 12px;
      border-radius: 6px;
      border: 1px solid var(--border-color);
      display: inline-flex;
      align-items: center;
      gap: 6px;
    }

    /* 2-Column Responsive Layout */
    .layout-grid {
      display: grid;
      grid-template-columns: 280px 1fr;
      gap: 24px;
      align-items: start;
    }

    /* Sidebar Sticky Navigation */
    .sidebar {
      position: sticky;
      top: 90px;
      display: flex;
      flex-direction: column;
      gap: 20px;
    }

    .sidebar-card {
      background: var(--bg-card);
      border-radius: var(--radius-card);
      padding: 20px;
      border: 1px solid var(--border-color);
      box-shadow: var(--shadow-card);
    }

    .sidebar-card-title {
      font-size: 15px;
      font-weight: 700;
      color: var(--primary-dark);
      margin-bottom: 14px;
      display: flex;
      align-items: center;
      gap: 8px;
    }

    .overview-list {
      list-style: none;
      display: flex;
      flex-direction: column;
      gap: 10px;
      font-size: 13px;
    }

    .overview-item {
      display: flex;
      justify-content: space-between;
      border-bottom: 1px dashed #F1F5F9;
      padding-bottom: 6px;
    }

    .overview-item span:first-child { color: var(--text-muted); }
    .overview-item span:last-child { font-weight: 600; color: var(--text-main); }

    .step-nav-list {
      list-style: none;
      display: flex;
      flex-direction: column;
      gap: 8px;
    }

    .step-nav-link {
      display: flex;
      align-items: center;
      gap: 10px;
      padding: 8px 12px;
      border-radius: var(--radius-sm);
      text-decoration: none;
      font-size: 13px;
      color: var(--text-secondary);
      font-weight: 500;
      transition: all 0.15s ease;
    }

    .step-nav-link:hover, .step-nav-link.active {
      background: var(--bg-soft-blue);
      color: var(--primary-blue);
      font-weight: 600;
    }

    .step-number-pill {
      width: 22px;
      height: 22px;
      border-radius: 50%;
      background: var(--border-color);
      color: var(--text-secondary);
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 11px;
      font-weight: 700;
    }

    .step-nav-link.active .step-number-pill {
      background: var(--primary-blue);
      color: white;
    }

    /* Content Area */
    .content-area {
      display: flex;
      flex-direction: column;
      gap: 24px;
    }

    .card-box {
      background: var(--bg-card);
      border-radius: var(--radius-card);
      padding: 28px;
      border: 1px solid var(--border-color);
      box-shadow: var(--shadow-card);
    }

    .card-box-header {
      display: flex;
      align-items: center;
      justify-content: space-between;
      margin-bottom: 20px;
      padding-bottom: 12px;
      border-bottom: 1px solid #F1F5F9;
    }

    .card-box-title {
      font-size: 18px;
      font-weight: 700;
      color: var(--primary-dark);
      display: flex;
      align-items: center;
      gap: 10px;
    }

    .math-display-container {
      font-size: 22px;
      padding: 20px;
      background: #FAFAFA;
      border-radius: 12px;
      border: 1px solid #F1F5F9;
      overflow-x: auto;
      margin: 12px 0;
      text-align: center;
    }

    /* Step Item Card */
    .step-card {
      position: relative;
      background: white;
      border-radius: var(--radius-card);
      padding: 24px;
      border: 1px solid var(--border-color);
      box-shadow: var(--shadow-card);
      transition: transform 0.2s ease, box-shadow 0.2s ease;
    }

    .step-card:hover {
      box-shadow: var(--shadow-hover);
    }

    .step-card-header {
      display: flex;
      align-items: center;
      justify-content: space-between;
      margin-bottom: 14px;
    }

    .step-badge-title {
      display: flex;
      align-items: center;
      gap: 12px;
    }

    .step-badge {
      width: 32px;
      height: 32px;
      background: var(--primary-blue);
      color: white;
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
      font-weight: 700;
      font-size: 14px;
    }

    .step-title {
      font-size: 16px;
      font-weight: 700;
      color: var(--primary-dark);
    }

    .step-explanation {
      font-size: 14px;
      color: var(--text-secondary);
      margin-bottom: 12px;
    }

    .step-note {
      font-size: 13px;
      background: var(--bg-soft-purple);
      color: #6B21A8;
      border-left: 3px solid #9333EA;
      padding: 8px 14px;
      border-radius: 6px;
      margin-top: 12px;
    }

    /* Final Answer Card */
    .final-answer-card {
      background: white;
      border-radius: var(--radius-card);
      border: 2px solid var(--primary-blue);
      box-shadow: var(--shadow-hover);
      overflow: hidden;
    }

    .final-answer-header {
      background: linear-gradient(135deg, var(--primary-dark) 0%, var(--primary-blue) 100%);
      color: white;
      padding: 16px 24px;
      display: flex;
      align-items: center;
      justify-content: space-between;
    }

    .final-answer-header h3 {
      font-size: 16px;
      font-weight: 700;
      letter-spacing: 0.05em;
      display: flex;
      align-items: center;
      gap: 10px;
    }

    .final-answer-body {
      padding: 32px;
      text-align: center;
    }

    .final-answer-latex {
      font-size: 32px;
      margin: 16px 0;
      color: var(--primary-dark);
    }

    .final-answer-actions {
      display: flex;
      justify-content: center;
      gap: 12px;
      margin-top: 20px;
    }

    /* Footer */
    .footer {
      background: white;
      border-top: 1px solid var(--border-color);
      margin-top: 60px;
      padding: 40px 24px;
    }

    .footer-container {
      max-width: 1440px;
      margin: 0 auto;
      display: flex;
      flex-wrap: wrap;
      justify-content: space-between;
      gap: 30px;
      font-size: 13px;
      color: var(--text-muted);
    }

    .toast {
      position: fixed;
      bottom: 24px;
      right: 24px;
      background: var(--text-main);
      color: white;
      padding: 12px 20px;
      border-radius: 8px;
      font-size: 14px;
      font-weight: 500;
      box-shadow: 0 10px 25px rgba(0,0,0,0.2);
      transform: translateY(100px);
      opacity: 0;
      transition: all 0.3s ease;
      z-index: 1000;
    }

    .toast.show {
      transform: translateY(0);
      opacity: 1;
    }

    /* Print Styles for PDF Export */
    @media print {
      .navbar, .nav-actions, .sidebar, .btn, .toast, .final-answer-actions, .footer-links {
        display: none !important;
      }
      body { background: white; padding: 0; }
      .layout-grid { grid-template-columns: 1fr; }
      .main-wrapper { max-width: 100%; padding: 0; }
      .card-box, .step-card, .final-answer-card {
        box-shadow: none !important;
        border: 1px solid #ccc !important;
        page-break-inside: avoid;
      }
    }

    /* Mobile Responsive Breakpoints */
    @media (max-width: 1024px) {
      .layout-grid { grid-template-columns: 1fr; }
      .sidebar { position: static; }
      .nav-links { display: none; }
      .mobile-menu-toggle { display: block; }
    }
  </style>
</head>
<body>

  <!-- Sticky Top Navigation -->
  <header class="navbar">
    <div class="nav-container">
      <a href="/" class="brand-logo">
        <div class="brand-icon"><i data-lucide="calculator"></i></div>
        <div>
          <div class="brand-title">Smart AI Math Solver</div>
          <div class="brand-subtitle" data-i18n="officialSolution">Official Solution Platform</div>
        </div>
      </a>

      <ul class="nav-links">
        <li><a href="/" data-i18n="navHome">Home</a></li>
        <li><a href="/solution/${publicId}" class="active" data-i18n="navSolutions">Solutions</a></li>
        <li><a href="/solution/demo123" data-i18n="navExamples">Examples</a></li>
        <li><a href="/#about" data-i18n="navAbout">About</a></li>
        <li><a href="/#contact" data-i18n="navContact">Contact</a></li>
      </ul>

      <div class="nav-actions">
        <div class="lang-switcher">
          <button class="lang-btn" id="lang-km" onclick="switchLanguage('km')">KH</button>
          <button class="lang-btn" id="lang-en" onclick="switchLanguage('en')">EN</button>
        </div>

        <button class="btn btn-outline" onclick="window.print()">
          <i data-lucide="download"></i> <span data-i18n="btnPdf">PDF</span>
        </button>
        <button class="btn btn-outline" onclick="shareSolution()">
          <i data-lucide="share-2"></i> <span data-i18n="btnShare">Share</span>
        </button>
        <a href="${telegramBotUrl}" target="_blank" rel="noopener noreferrer" class="btn btn-primary">
          <i data-lucide="send"></i> <span data-i18n="btnTelegram">Telegram Bot</span>
        </a>
      </div>
    </div>
  </header>

  <!-- Main Container -->
  <main class="main-wrapper">
    
    <!-- Solution Header Card -->
    <section class="solution-header-card">
      <div class="solution-title-box">
        <h1 data-i18n="solutionTitle">
          <i data-lucide="file-check-2" style="color: var(--primary-blue);"></i> 
          ${sanitizeHtmlText(data.title || 'ដំណោះស្រាយលំហាត់គណិតវិទ្យា')}
        </h1>
        <div class="meta-pills">
          <span class="verified-badge"><i data-lucide="check-circle-2"></i> <span data-i18n="verified">Verified Solution</span></span>
          <span class="meta-pill"><i data-lucide="hash"></i> #${publicId.toUpperCase()}</span>
          <span class="meta-pill"><i data-lucide="book-open"></i> ${sanitizeHtmlText(subject)}</span>
          <span class="meta-pill"><i data-lucide="calendar"></i> ${generatedAt}</span>
          <span class="meta-pill"><i data-lucide="clock"></i> ${generatedTime}</span>
        </div>
      </div>
    </section>

    <!-- 2-Column Responsive Layout -->
    <div class="layout-grid">

      <!-- Left Sidebar -->
      <aside class="sidebar">
        
        <!-- Problem Overview Card -->
        <div class="sidebar-card">
          <div class="sidebar-card-title">
            <i data-lucide="info" style="color: var(--primary-blue);"></i> 
            <span data-i18n="problemOverview">Problem Overview</span>
          </div>
          <ul class="overview-list">
            <li class="overview-item"><span data-i18n="subject">Subject</span><span>${sanitizeHtmlText(subject)}</span></li>
            <li class="overview-item"><span data-i18n="topic">Topic</span><span>${sanitizeHtmlText(topic)}</span></li>
            <li class="overview-item"><span data-i18n="difficulty">Difficulty</span><span>${sanitizeHtmlText(difficulty)}</span></li>
            <li class="overview-item"><span data-i18n="aiModel">AI Model</span><span>${sanitizeHtmlText(modelName)}</span></li>
          </ul>
        </div>

        <!-- Quick Summary Card -->
        <div class="sidebar-card">
          <div class="sidebar-card-title">
            <i data-lucide="zap" style="color: var(--status-warning);"></i> 
            <span data-i18n="quickSummary">Quick Summary</span>
          </div>
          <p style="font-size: 13px; color: var(--text-secondary);">${sanitizeHtmlText(summaryText)}</p>
        </div>

        <!-- Solution Steps Navigation Card -->
        <div class="sidebar-card">
          <div class="sidebar-card-title">
            <i data-lucide="list-ordered" style="color: var(--primary-blue);"></i> 
            <span data-i18n="stepsNavigation">Solution Steps</span>
          </div>
          <ul class="step-nav-list" id="step-nav-container">
            ${steps.map((st: any, idx: number) => `
              <li>
                <a href="#${st.id || 'step-' + (idx + 1)}" class="step-nav-link" id="nav-link-${idx + 1}">
                  <span class="step-number-pill">${idx + 1}</span>
                  <span>${sanitizeHtmlText(st.title || 'Step ' + (idx + 1))}</span>
                </a>
              </li>
            `).join('')}
          </ul>
        </div>

        <!-- Need Help Card -->
        <div class="sidebar-card" style="background: var(--bg-soft-blue); border-color: rgba(37, 99, 235, 0.2);">
          <div class="sidebar-card-title" style="color: var(--primary-blue);">
            <i data-lucide="help-circle"></i> 
            <span data-i18n="needHelp">Need Assistance?</span>
          </div>
          <p style="font-size: 13px; color: var(--text-secondary); margin-bottom: 12px;" data-i18n="helpDesc">
            Have questions about this solution? Chat directly with our AI assistant on Telegram!
          </p>
          <a href="${telegramBotUrl}" target="_blank" rel="noopener noreferrer" class="btn btn-primary" style="width: 100%; justify-content: center;">
            <i data-lucide="bot"></i> <span data-i18n="askAi">Ask AI Assistant</span>
          </a>
        </div>

      </aside>

      <!-- Main Content Area -->
      <section class="content-area">
        
        <!-- Problem Statement Card -->
        <div class="card-box">
          <div class="card-box-header">
            <div class="card-box-title">
              <i data-lucide="help-circle" style="color: var(--primary-blue);"></i>
              <span data-i18n="problemStatement">Problem Statement / ប្រធានលំហាត់</span>
            </div>
            <button class="btn btn-outline" onclick="copyText('${sanitizeHtmlText(problemRaw)}')">
              <i data-lucide="copy"></i> <span data-i18n="copyProblem">Copy</span>
            </button>
          </div>
          
          <div class="math-display-container">
            $$\\displaystyle ${problemLatex}$$
          </div>
        </div>

        <!-- Step-by-Step Solution Section -->
        <div class="card-box-title" style="font-size: 20px; margin-top: 10px;">
          <i data-lucide="layers" style="color: var(--primary-blue);"></i>
          <span data-i18n="stepByStep">Step-by-Step Solution / ដំណោះស្រាយជាជំហានៗ</span>
        </div>

        ${steps.map((st: any, idx: number) => `
          <article class="step-card" id="${st.id || 'step-' + (idx + 1)}">
            <div class="step-card-header">
              <div class="step-badge-title">
                <div class="step-badge">${idx + 1}</div>
                <div class="step-title">${sanitizeHtmlText(st.titleKh || st.title || 'Step ' + (idx + 1))}</div>
              </div>
              <button class="btn btn-outline" style="padding: 4px 10px; font-size: 12px;" onclick="copyText('${sanitizeHtmlText(st.latex || st.explanation)}')">
                <i data-lucide="copy"></i> <span data-i18n="copy">Copy</span>
              </button>
            </div>
            
            <p class="step-explanation">${sanitizeHtmlText(st.explanation)}</p>
            
            ${st.latex ? `<div class="math-display-container">$$\\displaystyle ${st.latex}$$</div>` : ''}
            
            ${st.note ? `<div class="step-note"><i data-lucide="info" style="display:inline; width:14px;"></i> ${sanitizeHtmlText(st.note)}</div>` : ''}
          </article>
        `).join('')}

        <!-- Final Answer Section -->
        <div class="final-answer-card">
          <div class="final-answer-header">
            <h3><i data-lucide="award"></i> <span data-i18n="finalAnswer">FINAL ANSWER / ចម្លើយចុងក្រោយ</span></h3>
            <span class="verified-badge" style="background: rgba(255,255,255,0.2); color: white; border: none;"><i data-lucide="check"></i> Verified</span>
          </div>
          <div class="final-answer-body">
            <div class="final-answer-latex">
              $$\\displaystyle ${finalAnswerLatex}$$
            </div>
            <p style="color: var(--status-success); font-weight: 600; font-size: 14px; margin-top: 10px;" data-i18n="successMsg">
              ✓ Solution simplified and verified successfully.
            </p>
            <div class="final-answer-actions">
              <button class="btn btn-outline" onclick="copyText('${sanitizeHtmlText(q1.final_answer_text || '1/2024')}')">
                <i data-lucide="copy"></i> <span data-i18n="copyAnswer">Copy Answer</span>
              </button>
              <button class="btn btn-outline" onclick="shareSolution()">
                <i data-lucide="share-2"></i> <span data-i18n="share">Share</span>
              </button>
              <button class="btn btn-primary" onclick="window.print()">
                <i data-lucide="download"></i> <span data-i18n="downloadPdf">Download PDF</span>
              </button>
            </div>
          </div>
        </div>

      </section>

    </div>

  </main>

  <!-- Official Footer -->
  <footer class="footer">
    <div class="footer-container">
      <div>
        <div style="font-weight: 700; color: var(--primary-dark); font-size: 16px; margin-bottom: 6px;">Smart AI Math Solver</div>
        <p style="max-width: 400px; line-height: 1.5;">
          AI-generated mathematical solution platform powered by Gemini 2.0 Flash. Important academic answers should be independently verified.
        </p>
      </div>
      <div>
        <div style="font-weight: 600; color: var(--text-main); margin-bottom: 8px;">Quick Links</div>
        <ul style="list-style: none; display: flex; flex-direction: column; gap: 6px;">
          <li><a href="/" style="color: var(--text-muted); text-decoration: none;">Home</a></li>
          <li><a href="/solution/demo123" style="color: var(--text-muted); text-decoration: none;">Demo Solution</a></li>
          <li><a href="${telegramBotUrl}" target="_blank" style="color: var(--text-muted); text-decoration: none;">Telegram Bot</a></li>
        </ul>
      </div>
      <div>
        <div style="font-weight: 600; color: var(--text-main); margin-bottom: 8px;">Legal & Attribution</div>
        <p>© 2026 Smart AI Math Solver. All rights reserved.</p>
      </div>
    </div>
  </footer>

  <!-- Toast Notification Container -->
  <div id="toast" class="toast">Action completed successfully</div>

  <!-- Client-side Interactive Scripts -->
  <script>
    // Initialize Lucide Icons
    lucide.createIcons();

    // Render KaTeX Math Expressions
    document.addEventListener("DOMContentLoaded", function() {
      renderMathInElement(document.body, {
        delimiters: [
          {left: "$$", right: "$$", display: true},
          {left: "$", right: "$", display: false}
        ],
        throwOnError : false
      });
    });

    // Language Dictionary
    const i18n = {
      km: {
        officialSolution: "វេទិកាដំណោះស្រាយផ្លូវការ",
        navHome: "ទំព័រដើម",
        navSolutions: "ដំណោះស្រាយ",
        navExamples: "ឧទាហរណ៍",
        navAbout: "អំពីយើង",
        navContact: "ទំនាក់ទំនង",
        btnPdf: "ទាញយក PDF",
        btnShare: "ចែករំលែក",
        btnTelegram: "Telegram Bot",
        solutionTitle: "ដំណោះស្រាយលំហាត់គណិតវិទ្យា",
        verified: "បានផ្ទៀងផ្ទាត់",
        problemOverview: "ព័ត៌មានទូទៅនៃលំហាត់",
        subject: "មុខវិជ្ជា",
        topic: "ប្រធានបទ",
        difficulty: "កម្រិត",
        aiModel: "ម៉ូឌែល AI",
        quickSummary: "សង្ខេបវិធីសាស្ត្រ",
        stepsNavigation: "ជំហាននៃដំណោះស្រាយ",
        needHelp: "ត្រូវការជំនួយបន្ថែម?",
        helpDesc: "មានសំណួរអំពីដំណោះស្រាយនេះ? អាចសួរ AI Assistant ផ្ទាល់លើ Telegram!",
        askAi: "សួរ AI Assistant",
        problemStatement: "ប្រធានលំហាត់ (Problem Statement)",
        copyProblem: "ចម្លង",
        stepByStep: "ដំណោះស្រាយជាជំហានៗ (Step-by-Step)",
        copy: "ចម្លង",
        finalAnswer: "ចម្លើយចុងក្រោយ (FINAL ANSWER)",
        copyAnswer: "ចម្លងចម្លើយ",
        share: "ចែករំលែក",
        downloadPdf: "ទាញយក PDF",
        successMsg: "✓ ដំណោះស្រាយត្រូវបានសម្រួល និងផ្ទៀងផ្ទាត់ត្រឹមត្រូវ។"
      },
      en: {
        officialSolution: "Official Solution Platform",
        navHome: "Home",
        navSolutions: "Solutions",
        navExamples: "Examples",
        navAbout: "About",
        navContact: "Contact",
        btnPdf: "PDF",
        btnShare: "Share",
        btnTelegram: "Telegram Bot",
        solutionTitle: "Mathematics Solution",
        verified: "Verified Solution",
        problemOverview: "Problem Overview",
        subject: "Subject",
        topic: "Topic",
        difficulty: "Difficulty",
        aiModel: "AI Model",
        quickSummary: "Quick Summary",
        stepsNavigation: "Solution Steps",
        needHelp: "Need Assistance?",
        helpDesc: "Have questions about this solution? Chat directly with our AI assistant on Telegram!",
        askAi: "Ask AI Assistant",
        problemStatement: "Problem Statement",
        copyProblem: "Copy",
        stepByStep: "Step-by-Step Solution",
        copy: "Copy",
        finalAnswer: "FINAL ANSWER",
        copyAnswer: "Copy Answer",
        share: "Share",
        downloadPdf: "Download PDF",
        successMsg: "✓ Solution simplified and verified successfully."
      }
    };

    let currentLang = localStorage.getItem('app_lang') || 'km';

    function switchLanguage(lang) {
      currentLang = lang;
      localStorage.setItem('app_lang', lang);
      document.querySelectorAll('.lang-btn').forEach(btn => btn.classList.remove('active'));
      document.getElementById('lang-' + lang).classList.add('active');

      const dict = i18n[lang];
      document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (dict[key]) el.textContent = dict[key];
      });
    }

    // Toast Feedback
    function showToast(msg) {
      const toast = document.getElementById('toast');
      toast.textContent = msg;
      toast.classList.add('show');
      setTimeout(() => toast.classList.remove('show'), 2500);
    }

    // Copy to Clipboard
    function copyText(str) {
      navigator.clipboard.writeText(str).then(() => {
        showToast(currentLang === 'km' ? 'បានចម្លងដោយជោគជ័យ!' : 'Copied to clipboard!');
      });
    }

    // Web Share API
    function shareSolution() {
      if (navigator.share) {
        navigator.share({
          title: 'Math Solution #${publicId}',
          text: 'Check out this math solution on Smart AI Math Solver!',
          url: window.location.href,
        }).catch(() => {});
      } else {
        copyText(window.location.href);
      }
    }

    // IntersectionObserver for Sidebar Step Highlighting
    document.addEventListener("DOMContentLoaded", function() {
      switchLanguage(currentLang);

      const stepCards = document.querySelectorAll('.step-card');
      const navLinks = document.querySelectorAll('.step-nav-link');

      const observer = new IntersectionObserver((entries) => {
        entries.forEach(entry => {
          if (entry.isIntersecting) {
            const id = entry.target.id;
            navLinks.forEach(link => {
              link.classList.toggle('active', link.getAttribute('href') === '#' + id);
            });
          }
        });
      }, { threshold: 0.5 });

      stepCards.forEach(card => observer.observe(card));
    });
  </script>

</body>
</html>`;
}
